# Generated by Django 6.0.7 on 2026-07-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('action', 'Jangari'), ('adventure', 'Sarguzasht'), ('comedy', 'Komediya'), ('drama', 'Drama'), ('fantasy', 'Fantastika'), ('romance', 'Romantika'), ('horror', "Qo'rqinchli")], max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
    ]
